# Generated by Django 4.2 on 2023-06-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aadharapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadharmodel',
            name='aadharno',
            field=models.IntegerField(unique=True),
        ),
    ]
